# Generated by Django 3.0.7 on 2022-02-03 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_first_name', models.CharField(max_length=100)),
                ('car_last_name', models.CharField(max_length=100)),
                ('car_id', models.IntegerField()),
                ('car_customer_need', models.CharField(max_length=100)),
                ('car_title', models.CharField(max_length=100)),
                ('car_city', models.CharField(max_length=100)),
                ('car_state', models.CharField(max_length=100)),
                ('car_email', models.EmailField(max_length=100)),
                ('car_phone', models.IntegerField()),
                ('car_message', models.TextField(blank=True)),
                ('user_id', models.IntegerField(blank=True)),
                ('create_date_message_notification', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 3, 9, 20, 25, 351315))),
            ],
        ),
    ]
