# Generated by Django 3.0.7 on 2022-02-05 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20220205_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='create_date_message_notification',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 5, 10, 59, 28, 510596)),
        ),
    ]
