# Generated by Django 3.0.7 on 2022-01-25 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20220125_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 25, 20, 38, 50, 144104)),
        ),
    ]
