# Generated by Django 3.0.7 on 2022-02-05 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20220205_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 5, 10, 59, 28, 509596)),
        ),
    ]
